name: Dogfood

on:
  push:
    branches: [main]
    paths:
      - ".github/settings.yml"
  workflow_dispatch:

jobs:
  settings:
    name: Update Settings
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Settings
        uses: ./
        with:
          token: ${{ secrets.PAT }}
